reset

diff --git a/.github/workflows/destroy_workflow.yaml b/.github/workflows/destroy_workflow.yaml
--- a/.github/workflows/destroy_workflow.yaml
+++ b/.github/workflows/destroy_workflow.yaml
@@ -38,18 +38,24 @@ jobs:
           TF_WORKSPACE: ${{ format('app-{0}', env.environment) }}
         id: plan
         run: |
+          set +e
           terraform plan -no-color -destroy -out plan.json > .output
-          url=$(grep '^To view this run' -A1 .output | grep -v '^To view this run' | tr -d '\012\015')
-          sm=$(grep -E '^(Plan:|No changes.)' .output | tr -d '\012\015')
-          echo "Run link: $url"
-          echo "Summary: $sm"
-          
-          echo "summary=$sm" >> $GITHUB_OUTPUT
+          if [ $? -ne 0 ]; then
+            echo "Destroy failed"
+            echo "failed=true" >> $GITHUB_OUTPUT
+          else
+            url=$(grep '^To view this run' -A1 .output | grep -v '^To view this run' | tr -d '\012\015')
+            sm=$(grep -E '^(Plan:|No changes.)' .output | tr -d '\012\015')
+            echo "Run link: $url"
+            echo "Summary: $sm"
+            
+            echo "summary=$sm" >> $GITHUB_OUTPUT
+          fi
           
       - name: Terraform Apply
         env:
           TF_WORKSPACE: ${{ format('app-{0}', env.environment) }}
-        if: ${{ !startsWith(steps.plan.outputs.summary, 'No changes.') }}
+        if: ${{ !steps.plan.outputs.failed == 'true' || !startsWith(steps.plan.outputs.summary, 'No changes.') }}
         run: |
           terraform apply plan.json -no-color > output
           echo "Run link: $(grep '^To view this run' -A1 output | grep -v '^To view this run' | tr -d '\012\015')"
@@ -57,6 +63,7 @@ jobs:
 
   infra_destroy:
     name: Destroy infrastructure
+    if: ${{ always() }}
     needs: app_destroy
     runs-on: ubuntu-latest
     defaults:
@@ -82,18 +89,24 @@ jobs:
           TF_WORKSPACE: ${{ format('infra-{0}', env.environment) }}
         id: plan
         run: |
+          set +e
           terraform plan -no-color -destroy -out plan.json -var-file=./environments/$environment/terraform.tfvars > .output
-          url=$(grep '^To view this run' -A1 .output | grep -v '^To view this run' | tr -d '\012\015')
-          sm=$(grep -E '^(Plan:|No changes.)' .output | tr -d '\012\015')
-          echo "Run link: $url"
-          echo "Summary: $sm"
-          
-          echo "summary=$sm" >> $GITHUB_OUTPUT
+          if [ $? -ne 0 ]; then
+            echo "Destroy failed"
+            echo "failed=true" >> $GITHUB_OUTPUT
+          else
+            url=$(grep '^To view this run' -A1 .output | grep -v '^To view this run' | tr -d '\012\015')
+            sm=$(grep -E '^(Plan:|No changes.)' .output | tr -d '\012\015')
+            echo "Run link: $url"
+            echo "Summary: $sm"
+            
+            echo "summary=$sm" >> $GITHUB_OUTPUT
+          fi
           
       - name: Terraform Apply
         env:
           TF_WORKSPACE: ${{ format('infra-{0}', env.environment) }}
-        if: ${{ !startsWith(steps.plan.outputs.summary, 'No changes.') }}
+        if: ${{ !steps.plan.outputs.failed == 'true' || !startsWith(steps.plan.outputs.summary, 'No changes.') }}
         run: |
           terraform apply plan.json -no-color > output
           echo "Run link: $(grep '^To view this run' -A1 output | grep -v '^To view this run' | tr -d '\012\015')"
