Update destroy_workflow.yaml

diff --git a/.github/workflows/destroy_workflow.yaml b/.github/workflows/destroy_workflow.yaml
--- a/.github/workflows/destroy_workflow.yaml
+++ b/.github/workflows/destroy_workflow.yaml
@@ -38,13 +38,18 @@ jobs:
           TF_WORKSPACE: ${{ format('app-{0}', env.environment) }}
         id: plan
         run: |
+          set +e
           terraform plan -no-color -destroy -out plan.json > .output
-          url=$(grep '^To view this run' -A1 .output | grep -v '^To view this run' | tr -d '\012\015')
-          sm=$(grep -E '^(Plan:|No changes.)' .output | tr -d '\012\015')
-          echo "Run link: $url"
-          echo "Summary: $sm"
-          
-          echo "summary=$sm" >> $GITHUB_OUTPUT
+          if [ $? -ne 0 ]; then
+            echo "Destroy failed"
+          else
+            url=$(grep '^To view this run' -A1 .output | grep -v '^To view this run' | tr -d '\012\015')
+            sm=$(grep -E '^(Plan:|No changes.)' .output | tr -d '\012\015')
+            echo "Run link: $url"
+            echo "Summary: $sm"
+            
+            echo "summary=$sm" >> $GITHUB_OUTPUT
+          fi
           
       - name: Terraform Apply
         env:
@@ -82,14 +87,18 @@ jobs:
           TF_WORKSPACE: ${{ format('infra-{0}', env.environment) }}
         id: plan
         run: |
+          set +e
           terraform plan -no-color -destroy -out plan.json -var-file=./environments/$environment/terraform.tfvars > .output
-          url=$(grep '^To view this run' -A1 .output | grep -v '^To view this run' | tr -d '\012\015')
-          sm=$(grep -E '^(Plan:|No changes.)' .output | tr -d '\012\015')
-          echo "Run link: $url"
-          echo "Summary: $sm"
-          
-          echo "summary=$sm" >> $GITHUB_OUTPUT
-          
+          if [ $? -ne 0 ]; then
+            echo "Destroy failed"
+          else
+            url=$(grep '^To view this run' -A1 .output | grep -v '^To view this run' | tr -d '\012\015')
+            sm=$(grep -E '^(Plan:|No changes.)' .output | tr -d '\012\015')
+            echo "Run link: $url"
+            echo "Summary: $sm"
+            
+            echo "summary=$sm" >> $GITHUB_OUTPUT
+          fi
       - name: Terraform Apply
         env:
           TF_WORKSPACE: ${{ format('infra-{0}', env.environment) }}
