change version testing 1/2

diff --git a/.github/workflows/ps_workflow.yaml b/.github/workflows/ps_workflow.yaml
--- a/.github/workflows/ps_workflow.yaml
+++ b/.github/workflows/ps_workflow.yaml
@@ -131,7 +131,7 @@ jobs:
     name: Push helm chart
     needs: [ changed_files, infra_build ] 
     outputs:
-      chart_version: ${{ steps.modify.outputs.chart_version || 'latest' }}
+      chart_version: ${{ steps.modify.outputs.chart_version }}
     runs-on: ubuntu-latest
     defaults:
       run:
@@ -182,7 +182,7 @@ jobs:
     name: Push docker image
     needs: [ changed_files, infra_build ] 
     outputs:
-      image_tag: ${{ steps.push.outputs.image_tag || 'latest' }}
+      image_tag: ${{ steps.push.outputs.image_tag }}
     runs-on: ubuntu-latest
     defaults:
       run:
@@ -251,21 +251,47 @@ jobs:
             echo $infra_outputs | sed -nE "s/(^|.*;)($var.*$)/\2/p" | sed -n "s/;.*//p" >> terraform.tfvars
           done
 
-      - name: Update image tag
-        run: |
-          echo "${{ needs.image_push.outputs.image_tag }}"
-          echo "image_tag = \"${{ needs.image_push.outputs.image_tag }}\"" >> terraform.tfvars
-
-      - name: Update chart version
-        run: |
-          echo "${{ needs.chart_push.outputs.chart_version }}"
-          echo "chart_version = \"${{ needs.chart_push.outputs.chart_version }}\"" >> terraform.tfvars
-
       - name: Terraform Init
         env:
           TF_WORKSPACE: ${{ format('app-{0}', env.environment) }}
         run: |
           terraform init
+
+      - name: Update image tag
+        env:
+          TF_WORKSPACE: ${{ format('app-{0}', env.environment) }}
+        run: |
+          if [[ ${{ needs.changed_files.outputs.images }} == true ]] ;then
+            echo "iamges will change!"
+            echo "image_tag = \"${{ needs.image_push.outputs.image_tag }}\"" >> terraform.tfvars
+          else
+            echo "iamges won't change!"
+            value="\"$(terraform output -raw image_tag 2>.err)\""
+            if [ $? -ne 0 ] && grep -q "Output \"image_tag\" not found" .err; then
+              echo "can't find previous image_tag's value"
+            else
+              echo "image_tag = $value" >> terraform.tfvars
+              echo "found previous image_tag's value"
+            fi
+          fi
+
+      - name: Update chart version
+        env:
+          TF_WORKSPACE: ${{ format('app-{0}', env.environment) }}
+        run: |
+          if [[ ${{ needs.changed_files.outputs.charts }} == true ]] ;then
+            echo "charts will change!"
+            echo "chart_version = \"${{ needs.chart_push.outputs.chart_version }}\"" >> terraform.tfvars
+          else
+            echo "charts won't change!"
+            value="\"$(terraform output -raw chart_version 2>.err)\""
+            if [ $? -ne 0 ] && grep -q "Output \"chart_version\" not found" .err; then
+              echo "can't find previous chart_version's value"
+            else
+              echo "chart_version = $value" >> terraform.tfvars
+              echo "found previous chart_version's value"
+            fi
+          fi
 
       # run terraform plan and save plan to apply
       - name: Terraform plan
